### ISSUE TITLE
Develop a roadmap for Public Cloud service for 23-24 fiscal

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2263]
This is an Epic that will be tracking all work related to developing a roadmap for the Cloud Pathfinder team for the next fiscal year. It will include activities related to preparing a plan for internal and external engagement to collect feedback about team's priorities, running the engagement and analysing the results, and finally producing a roadmap [in the following format](https://app.mural.co/t/platformservices5977/m/platformservices5977/1655147846464/1318e74c5bd5bba3e6370012968f0182d04e3631?sender=u1d0b96ff3161eda8f0f38743)

**Definition of done**
A tentative plan (Gautam - please create tickets for the steps below as they get fleshed out)
- [ ] connect with Martha Edwards to learn from her about the approach taken to develop the 22/23 roadmap for Private Cloud and the tools used for engagement 
- [ ] Get access to the service design tools used by Platform Services Team i.e. Mural, Optimal , SurveyMonkey (Alexandra Lloyd, Service Design Lead on the team,  can help with that)
- [ ] Prepare a Mural board for the internal roadmap development workshop and book the workshop
- [ ] Run the internal workshop with the CPF team 
- [ ] Create a spreadsheet with the priorities that were identified by the team and work with the PO and Tech Lead to aggregate them into the 20-30 high level priorities.
- [ ] Create a card sorting activity in Optimal using the high level priorities from the step above
- [ ] Prepare and send out the invite to participate in the card sorting activity to all teams working in Public and Private Cloud (Olena can help get the contacts and to send the email)
- [ ] Using the ordered priorities from the card sorting exercise, create a roadmap in Mural
