### ISSUE TITLE
Update AWS SoAR

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2729]
**Describe the Issue**
AWS SoAR was initially created about 2 years ago.  A lot has changed since that point with respect to configurations, automation and control.  

**Additional Context**
SoAR has almost 40 items listed.  To break this up into 2 pieces to reduce effort to be possible in a sprint with other tasks.

**Acceptance Criteria**
- [ ] Review existing SoAR
- [ ] Remove items that should not be in scope (i.e. supporting services that would be run by Ministries alone and/or reviewed already by SSC)
- [ ] Update status/controls for platform controls
- [ ] Update target dates for uncompleted items
