### ISSUE TITLE
Perimeter Jump host automation

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2863]
**Describe the Issue**
Perimeter Jump host automation

**Additional Context**
Prabhu can assist.
The instance requires an instance profile that has access to the backup S3 bucket

**Acceptance Criteria**

- [ ] Deploy the instance with IaC
- [ ] Automate configuration of the instance
- [ ] Smart console
- [ ] Backup script
- [ ] Create a backup S3 with IaC

**Comment by bruce-wh-li** [comment]
We can first backup the EC2 image just in case and prioritize the ticket later.  
@prabhukiran9999 @wrnu, what do you think ?

**Comment by wrnu** [comment]
Before we do anything in Live we want to have the entire infrastructure deployment and configuration implemented with automation.

By doing this now we will reduce our risk and effort later.

**Comment by bruce-wh-li** [comment]
I think this should be a Epic.   5 does not justify the effort required to build the total solution even we got the firewall backup/restore part figured out , I think.  Maybe split to 5 tickets, e.g. 1. infrastructure using terraform, terrgrunt. 2. configuration, depending component using ansible, 3. ci/cd pipeline 4. integration test 5. documentation.

**Comment by wrnu** [comment]
That is a good breakdown of the tasks needed. I'm ok with breaking it up, the points assigned can also be adjusted.

CI/CD for the IaC is is handled by the overlay repo, we may want something separate for the configuration but we can discuss that further.

Also in case it isn't clear, @prabhukiran9999 will be assisting with the development.
