### ISSUE TITLE
LZA Implement new account vending

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2944]
- [ ] Set up CI/CD
- [ ] There is no state machine trigger on account creation in the LZA and accounts must be created using the LZA config file.
- [ ] Create a new provisioner for the LZA with new account creation workflow
